# LinkEditor documentation
# https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-string-or-object-neos-neos-domain-link-link-linkeditor-link-editor-for-all-types-of-links

Neos:
  Neos:
    nodeTypes:
      presets:
        properties:
          link:

            general:
              type: string
              ui:
                label: i18n
                reloadIfChanged: true
                inspector:
                  position: 300
                  editor: 'Neos.Neos/Inspector/Editors/LinkEditor'
